//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimClient.ClaimServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Citizen", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class Citizen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassAgencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PassDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TpinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassAgency {
            get {
                return this.PassAgencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PassAgencyField, value) != true)) {
                    this.PassAgencyField = value;
                    this.RaisePropertyChanged("PassAgency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PassDate {
            get {
                return this.PassDateField;
            }
            set {
                if ((this.PassDateField.Equals(value) != true)) {
                    this.PassDateField = value;
                    this.RaisePropertyChanged("PassDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassNumber {
            get {
                return this.PassNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassNumberField, value) != true)) {
                    this.PassNumberField = value;
                    this.RaisePropertyChanged("PassNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassSeries {
            get {
                return this.PassSeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.PassSeriesField, value) != true)) {
                    this.PassSeriesField = value;
                    this.RaisePropertyChanged("PassSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tpin {
            get {
                return this.TpinField;
            }
            set {
                if ((object.ReferenceEquals(this.TpinField, value) != true)) {
                    this.TpinField = value;
                    this.RaisePropertyChanged("Tpin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClaimClient.ClaimServiceReference.ClaimLifeCycle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClaimClient.ClaimServiceReference.ClaimList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClaimClient.ClaimServiceReference.ClaimId))]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClaimClient.ClaimServiceReference.ErrorCode ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClaimClient.ClaimServiceReference.ErrorCode ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((this.ErrCodeField.Equals(value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimLifeCycle", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class ClaimLifeCycle : ClaimClient.ClaimServiceReference.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClaimClient.ClaimServiceReference.ClaimStatus[] valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClaimClient.ClaimServiceReference.ClaimStatus[] value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimList", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class ClaimList : ClaimClient.ClaimServiceReference.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClaimClient.ClaimServiceReference.ClaimInfo[] valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClaimClient.ClaimServiceReference.ClaimInfo[] value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimId", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class ClaimId : ClaimClient.ClaimServiceReference.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InputDataFormat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimStatus", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class ClaimStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimInfo", Namespace="http://schemas.datacontract.org/2004/07/ClaimsSystem")]
    [System.SerializableAttribute()]
    public partial class ClaimInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenName {
            get {
                return this.CitizenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenNameField, value) != true)) {
                    this.CitizenNameField = value;
                    this.RaisePropertyChanged("CitizenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimId {
            get {
                return this.ClaimIdField;
            }
            set {
                if ((this.ClaimIdField.Equals(value) != true)) {
                    this.ClaimIdField = value;
                    this.RaisePropertyChanged("ClaimId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClaimServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addClaim", ReplyAction="http://tempuri.org/IService1/addClaimResponse")]
        ClaimClient.ClaimServiceReference.ClaimId addClaim(ClaimClient.ClaimServiceReference.Citizen citizen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addClaim", ReplyAction="http://tempuri.org/IService1/addClaimResponse")]
        System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimId> addClaimAsync(ClaimClient.ClaimServiceReference.Citizen citizen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClaimLifeCycle", ReplyAction="http://tempuri.org/IService1/getClaimLifeCycleResponse")]
        ClaimClient.ClaimServiceReference.ClaimLifeCycle getClaimLifeCycle(int claimId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClaimLifeCycle", ReplyAction="http://tempuri.org/IService1/getClaimLifeCycleResponse")]
        System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimLifeCycle> getClaimLifeCycleAsync(int claimId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClaimList", ReplyAction="http://tempuri.org/IService1/getClaimListResponse")]
        ClaimClient.ClaimServiceReference.ClaimList getClaimList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getClaimList", ReplyAction="http://tempuri.org/IService1/getClaimListResponse")]
        System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimList> getClaimListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClaimClient.ClaimServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClaimClient.ClaimServiceReference.IService1>, ClaimClient.ClaimServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClaimClient.ClaimServiceReference.ClaimId addClaim(ClaimClient.ClaimServiceReference.Citizen citizen) {
            return base.Channel.addClaim(citizen);
        }
        
        public System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimId> addClaimAsync(ClaimClient.ClaimServiceReference.Citizen citizen) {
            return base.Channel.addClaimAsync(citizen);
        }
        
        public ClaimClient.ClaimServiceReference.ClaimLifeCycle getClaimLifeCycle(int claimId) {
            return base.Channel.getClaimLifeCycle(claimId);
        }
        
        public System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimLifeCycle> getClaimLifeCycleAsync(int claimId) {
            return base.Channel.getClaimLifeCycleAsync(claimId);
        }
        
        public ClaimClient.ClaimServiceReference.ClaimList getClaimList() {
            return base.Channel.getClaimList();
        }
        
        public System.Threading.Tasks.Task<ClaimClient.ClaimServiceReference.ClaimList> getClaimListAsync() {
            return base.Channel.getClaimListAsync();
        }
    }
}
